# Generated by Django 5.0.6 on 2024-06-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="slug",
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
